(() => {
"use strict";
const DEFAULTS={enabled:true,delay:500,count:0};let settings={...DEFAULTS},lastClick=0,pendingTimer=null;
const norm=v=>(v||"").replace(/\s+/g," ").trim().toLowerCase();
const visible=e=>{if(!e)return false;const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=="none"&&s.visibility!=="hidden"&&r.width>0&&r.height>0};
const isContinue=t=>["continue watching","yes, continue watching","lanjut menonton","ya, lanjut menonton"].some(x=>t===x||t.includes(x));
function toast(){const old=document.getElementById("axy-ply-toast");if(old)old.remove();const e=document.createElement("div");e.id="axy-ply-toast";e.textContent="AxyPly ✓ Video dilanjutkan";Object.assign(e.style,{position:"fixed",top:"18px",right:"18px",zIndex:"2147483647",padding:"10px 14px",borderRadius:"12px",background:"rgba(15,15,15,.94)",color:"#fff",font:"600 13px system-ui,sans-serif",boxShadow:"0 6px 24px rgba(0,0,0,.3)",opacity:"0",transform:"translateY(-6px)",transition:"all .2s ease"});document.documentElement.appendChild(e);requestAnimationFrame(()=>{e.style.opacity="1";e.style.transform="translateY(0)"});setTimeout(()=>{e.style.opacity="0";e.style.transform="translateY(-6px)";setTimeout(()=>e.remove(),220)},1500)}
function clickButton(b){if(!settings.enabled||!visible(b))return;const n=Date.now();if(n-lastClick<1800)return;lastClick=n;clearTimeout(pendingTimer);pendingTimer=setTimeout(()=>{if(!visible(b))return;b.click();try{["mousedown","mouseup","click"].forEach(t=>b.dispatchEvent(new MouseEvent(t,{bubbles:true,cancelable:true,view:window})))}catch(_){}settings.count++;chrome.storage.local.set({count:settings.count});toast()},Math.max(0,Number(settings.delay)||0))}
function check(){if(!settings.enabled)return;const q="yt-confirm-dialog-renderer button,tp-yt-paper-dialog button,[role='dialog'] button,yt-confirm-dialog-renderer [role='button'],tp-yt-paper-dialog [role='button'],[role='dialog'] [role='button']";for(const e of document.querySelectorAll(q)){if(!visible(e))continue;const t=norm(e.innerText||e.textContent),d=e.closest("yt-confirm-dialog-renderer,tp-yt-paper-dialog,[role='dialog']");if(isContinue(t)||(d&&/^(yes|ya)$/i.test(t))){clickButton(e);return}}}
chrome.storage.local.get(DEFAULTS,d=>{settings={...DEFAULTS,...d};check()});chrome.storage.onChanged.addListener(c=>{for(const[k,v]of Object.entries(c))settings[k]=v.newValue});
new MutationObserver(check).observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:["hidden","aria-hidden","style","class"]});setInterval(check,2500);setTimeout(check,1000);setTimeout(check,3000);
})();